In [ ]:
import pandas as pd

In [ ]:
#Upload file "genes.csv" which is derived from HORDE database (https://genome.weizmann.ac.il/horde/app/webroot/index.php/)
from google.colab import files
uploaded = files.upload()

Saving genes.csv to genes.csv

In [ ]:
OR_genes = pd.read_csv("genes.csv", sep = ";")
print(OR_genes.shape)
print(OR_genes.head())

(857, 17)
    Id  Symbol  Family Id Sub Family  Pseduo Gene                 Comments  \
0   51   OR1C1          1          C            0                      NaN
1  151  OR1X1P          1          X            1  Disrupted by Alu repeat
2  152  OR1X5P          1          X            1  Disrupted by Alu repeat
3  166  OR1F12          1          F            0                      NaN
4  267   OR1J1          1          J            0                      NaN

   Pseduo Probability                                Nucleotide Sequence  \
0                0.01  ATGGAAAAAAGAAATCTAACAGTTGTCAGGGAATTCGTCCTTCTGG...
1                0.00  GGGGGTAAAGAGAATGAGACAGGAGTTGGCGAGTTCCTCTTGCTCA...
2                0.00  ATGTCCAGGGGTAAAGAGAATGAGACAGGAGTTGGCGAGTTCCTCT...
3                0.04  ATGGAAGGGAAAAATCAAACCAATATCTCTGAATTTCTCCTCCTGG...
4                0.09  ATGAGCCCTGAGAACCAGAGCAGCGTGTCCGAGTTCCTCCTCCTGG...

                                 Conceptual Sequence  Clic  Horde Id  \
0  MEKRNLTVVREFVLLGLPSSAEQQHLLSVLFLCMYLATTLGNMLII...     5       808
1  GGKENETGVGEFLLLSITSDSEKQQALFWLFLCMHLVTEAGNTPII...     0       387
2  MSRGKENETGVGEFLLLGITSDSGKQQALFWLFLCMHLVTEAGNTP...     0      1060
3  MEGKNQTNISEFLLLGFSSWQQQQVLLFALFLCLYLTGLFGNLLIL...    12       302
4  MSPENQSSVSEFLLLGLPIRPEQQAVFFALFLGMYLTTVLGNLLIM...    21       521

  Chromosome        Start          End Strand            Synteny   Name
0          1  247757465.0  247758406.0      -  0.01 (functional)  1@248
1          5  176006145.0  176007389.0      +                NaN  5@175
2          5  177836413.0  177837664.0      -                NaN  5@177
3          6   28073316.0   28074236.0      +  0.04 (functional)  6@28a
4          9  122477009.0  122477926.0      -  0.09 (functional)  9@125

In [ ]:
OR_genes['Pseduo Gene'].value_counts()

Pseduo Gene
1    466
0    391
Name: count, dtype: int64

In [ ]:
mask_not_pseudo = ~OR_genes['Symbol'].str.strip().str.endswith('P')
print(mask_not_pseudo)

0       True
1      False
2      False
3       True
4       True
       ...
852     True
853     True
854    False
855     True
856    False
Name: Symbol, Length: 857, dtype: bool

In [ ]:
df_filtered = OR_genes[mask_not_pseudo].copy()

In [ ]:
print(df_filtered)

      Id  Symbol  Family Id Sub Family  Pseduo Gene Comments  \
0     51   OR1C1          1          C            0      NaN
3    166  OR1F12          1          F            0      NaN
4    267   OR1J1          1          J            0      NaN
5    268   OR1J2          1          J            0      NaN
6    269   OR1J4          1          J            0      NaN
..   ...     ...        ...        ...          ...      ...
850  383  OR56A3         56          A            0      NaN
851  384  OR56A5         56          A            0      NaN
852  386  OR56A4         56          A            0      NaN
853  387  OR56A1         56          A            0      NaN
855  391  OR56B4         56          B            0      NaN

     Pseduo Probability                                Nucleotide Sequence  \
0                  0.01  ATGGAAAAAAGAAATCTAACAGTTGTCAGGGAATTCGTCCTTCTGG...
3                  0.04  ATGGAAGGGAAAAATCAAACCAATATCTCTGAATTTCTCCTCCTGG...
4                  0.09  ATGAGCCCTGAGAACCAGAGCAGCGTGTCCGAGTTCCTCCTCCTGG...
5                  0.02  ATGAGCCCTGAGAACCAGAGCAGCGTGTCCGAGTTCCTCCTTCTGG...
6                  0.32  ATGAAGAGGGAGAATCAGAGCAGTGTGTCTGAGTTCCTCCTCCTGG...
..                  ...                                                ...
850                0.54  ATGACAACACACCGAAATGACACCCTCTCCACTGAAGCTTCAGACT...
851                0.49  ATGACATTACCCAGCAACAACTCCACTTCCCCAGTCTTTGAATTCT...
852                0.49  ATGGCATCTCCCAGCAATGACTCCACTGCCCCAGTCTCTGAATTCC...
853                0.60  ATGGCGTCACCCAGCAACAGCTCCACTGTCCCAGTCTCTGAATTCC...
855                0.03  ATGGATACCTCCACCAGTGTTACCTATGACTCCAGCCTCCAGATTT...

                                   Conceptual Sequence  Clic  Horde Id  \
0    MEKRNLTVVREFVLLGLPSSAEQQHLLSVLFLCMYLATTLGNMLII...     5       808
3    MEGKNQTNISEFLLLGFSSWQQQQVLLFALFLCLYLTGLFGNLLIL...    12       302
4    MSPENQSSVSEFLLLGLPIRPEQQAVFFALFLGMYLTTVLGNLLIM...    21       521
5    MSPENQSSVSEFLLLGLPIRPEQQAVFFTLFLGMYLTTVLGNLLIM...    21       519
6    MKRENQSSVSEFLLLDLPIWPEQQAVFFTLFLGMYLITVLGNLLII...    21       539
..                                                 ...   ...       ...
850  MTTHRNDTLSTEASDFLLNCFVRSPSWQHWLSLPLSLLFLLAVGAN...    23       250
851  MTLPSNNSTSPVFEFFLICFPSFQSWQHWLSLPLSLLFLLAMGANA...    23       152
852  MASPSNDSTAPVSEFLLICFPNFQSWQHWLSLPLSLLFLLAMGANT...    23       151
853  MASPSNSSTVPVSEFLLICFPNFQSWQHWLSLPLSLLFLLAMGANT...    23       138
855  MDTSTSVTYDSSLQISQFILMGLPGIHEWQHWLSLPLTLLYLLALG...    23       431

    Chromosome        Start          End Strand            Synteny   Name
0            1  247757465.0  247758406.0      -  0.01 (functional)  1@248
3            6   28073316.0   28074236.0      +  0.04 (functional)  6@28a
4            9  122477009.0  122477926.0      -  0.09 (functional)  9@125
5            9  122510802.0  122511740.0      +  0.02 (functional)  9@125
6            9  122519141.0  122520079.0      +  0.32 (functional)  9@125
..         ...          ...          ...    ...                ...    ...
850         11    5947347.0    5948291.0      +  0.54 (pseudogene)   11@6
851         11    5967556.0    5968494.0      -  0.49 (functional)   11@6
852         11    6002054.0    6002992.0      -  0.49 (functional)   11@6
853         11    6026751.0    6027692.0      -   0.6 (pseudogene)   11@6
855         11    6107779.0    6108735.0      +  0.03 (functional)   11@6

[391 rows x 17 columns]

In [ ]:
df_filtered['Pseduo Gene'].value_counts()

Pseduo Gene
0    391
Name: count, dtype: int64

In [ ]:
removed = OR_genes[~mask_not_pseudo]
print(removed)

      Id   Symbol  Family Id Sub Family  Pseduo Gene  \
1    151   OR1X1P          1          X            1
2    152   OR1X5P          1          X            1
10   273   OR1H1P          1          H            1
21   773   OR1F2P          1          F            1
24   777   OR1E3P          1          E            1
..   ...      ...        ...        ...          ...
844  393  OR52B1P         52          B            1
847  293  OR55B1P         55          B            1
849  372  OR56B2P         56          B            1
854  388  OR56A7P         56          A            1
856  392  OR56B3P         56          B            1

                                              Comments  Pseduo Probability  \
1                              Disrupted by Alu repeat                 0.0
2                              Disrupted by Alu repeat                 0.0
10                                                 NaN                 0.0
21                                                 NaN                 0.0
24   Segregating Pseudo Gene, a polymorphism of C->...                 0.0
..                                                 ...                 ...
844                                                NaN                 0.0
847                                                NaN                 0.0
849                         Coding for partial protein                 0.0
854                                                NaN                 0.0
856                                                NaN                 0.0

                                   Nucleotide Sequence  \
1    GGGGGTAAAGAGAATGAGACAGGAGTTGGCGAGTTCCTCTTGCTCA...
2    ATGTCCAGGGGTAAAGAGAATGAGACAGGAGTTGGCGAGTTCCTCT...
10   ATGGACAGAAGAAACCAGACCTGCATCTATGAATTTCTTCTCATGG...
21   GTATGTTTCTGAATTCACTGTCTTCTATGCAGCTGGGTCCAGACAT...
24   ATGATGAAGAAGAACCAAACCATGATCTCAGAGTTCCTGCTCCTGG...
..                                                 ...
844  ATGTTTGGTGCTAATCTCACCACCTTCCATCCCACTCTATTCATTC...
847  ATGGGTGAGGATGGAAATACAAGCACCTTCAACATCTCCTGCACCA...
849  ATGGGATTCCCTGGCATTCACAGTTGGCAGCACTGGCTCTCCCTGC...
854  ATGACATTACCCAGCGATGACTCCACTGTCCCAGTCTCTGAATTCC...
856  ATGGATATTGGCCTGAGTATAGCCAATAGCTCAGGGTTTCAACTGT...

                                   Conceptual Sequence  Clic  Horde Id  \
1    GGKENETGVGEFLLLSITSDSEKQQALFWLFLCMHLVTEAGNTPII...     0       387
2    MSRGKENETGVGEFLLLGITSDSGKQQALFWLFLCMHLVTEAGNTP...     0      1060
10   MDRRNQTCIYEFLLMGFSEHQEQQALLFGLFLVMYLVTVLENLLII...    21       452
21   VCFXIHCLLCSWVQTYERDKPVSVSEFLLLGLSRQPQQQHLLFVFF...    38        16
24   MMKKNQTMISEFLLLGL/PIQPEQQNLFYALFLAVYLTTLLGNLLV...    39        96
..                                                 ...   ...       ...
844  MFGANLTTFHPTLFILLGIPGLEQYHIWLSIPFYLMYITAVLGNGA...    23       428
847  MGEDGNTSTFNISCTKFFLVGFPGLREWWPLLVLPLVFLFVTIISA...    23       725
849  MGFPGIHSWQHWLSLPLALLYLLALSANILILIIINKEAALHQPMY...    23       280
854  MTLPSDDSTVPVSEFLLICFPNFQSWQHLLSLPLSLLSSWPWGPTP...    23       816
856  MDIGLSIANSSGFQLSEFILIGFPGIHEWQHWLSLPLALGANLLII...    23       424

    Chromosome        Start          End Strand Synteny   Name
1            5  176006145.0  176007389.0      +     NaN  5@175
2            5  177836413.0  177837664.0      -     NaN  5@177
10           9  122607864.0  122608797.0      +     NaN  9@125
21          16    3215566.0    3216546.0      +     NaN   16@3
24          17    3116427.0    3117403.0      +     NaN  17@3b
..         ...          ...          ...    ...     ...    ...
844         11    6151595.0    6152549.0      -     NaN   11@6
847         11    4146316.0    4147295.0      -     NaN  11@4b
849         11    5765162.0    5766046.0      +     NaN   11@6
854         11    6045810.0    6046747.0      -     NaN   11@6
856         11    6128610.0    6129553.0      +     NaN   11@6

[466 rows x 17 columns]

In [ ]:
removed['Pseduo Gene'].value_counts()

Pseduo Gene
1    466
Name: count, dtype: int64

In [ ]:
print(removed.shape)

(466, 17)

In [ ]:
family_col = 'Family Id'
gene_col = 'Symbol'

gene_sets = (
    df_filtered
    .groupby(family_col)[gene_col]
    .apply(lambda x: sorted(x.dropna().unique().tolist()))
)

print(f"Number of families: {len(gene_sets)}")
for fam, genes in gene_sets.items():
    print(f"  OR_fam{fam}: {len(genes)} genes")

Number of families: 17
  OR_fam1: 28 genes
  OR_fam2: 68 genes
  OR_fam3: 4 genes
  OR_fam4: 51 genes
  OR_fam5: 47 genes
  OR_fam6: 30 genes
  OR_fam7: 11 genes
  OR_fam8: 24 genes
  OR_fam9: 9 genes
  OR_fam10: 36 genes
  OR_fam11: 8 genes
  OR_fam12: 2 genes
  OR_fam13: 12 genes
  OR_fam14: 6 genes
  OR_fam51: 23 genes
  OR_fam52: 26 genes
  OR_fam56: 6 genes

In [ ]:
output_path = "human_OR_families_noPseudo.gmt"

with open(output_path, "w", newline="\n") as f:
    for fam_id, genes in gene_sets.items():
        set_name = f"OR_fam{fam_id}"
        description = "na"  # placeholder
        line = "\t".join([set_name, description] + genes)
        f.write(line + "\n")

print(f"GMT file saved: {output_path}")

GMT file saved: human_OR_families_noPseudo.gmt

In [ ]:
from google.colab import files

files.download("human_OR_families_noPseudo.gmt")